### ISSUE TITLE
Incomplete code of existing programs.

### ISSUE THREAD

**Issue by SubhradeepSS** [dibyendu415/DibsProjects#4]
@dibyendu415 I would like to complete the existing programs.
Please assign me.

**Comment by himanshusharma89** [comment]
I would like to contribute to this issue. You can assign me for this.

**Comment by satyamroy001** [comment]
i would like to contribute you can assign me for this

**Comment by Sambhu98** [comment]
I would like to contribute to this issue. You can assign me for this.
